language: go
env:
  - BUILD_VERSION=travis-CI
before_install:
  - sudo curl -Lo /usr/local/bin/solc https://github.com/ethereum/solidity/releases/download/v0.4.25/solc-static-linux
after_success:
  - bash <(curl -s https://codecov.io/bash)
go:
  - "1.11.x"

