language: go
env:
  - BUILD_VERSION=travis-CI GO111MODULE=on
before_install:
  - sudo curl -Lo /usr/local/bin/solc https://github.com/ethereum/solidity/releases/download/v0.7.6/solc-static-linux
  - sudo chmod 755 /usr/local/bin/solc
  - mv go.mod go.mod.orig
  - grep -v ethbinding go.mod.orig > go.mod
  - go get github.com/kaleido-io/ethbinding
  - make ethbinding.so
after_success:
  - bash <(curl -s https://codecov.io/bash)
go:
  - "1.16.x"

