coverage:
  status:
    project:
      default:
        threshold: 0.1%
    patch:
      default:
        threshold: 0.1%
  ignore:
  - "internal/eth" # Dynamic dependency library loading - relied on by other tests
  - "internal/kafka/mock_sarama" # Generated mock
  - "internal/auth/authtest" # Mock
  - "cmd/plugins.go" # Not testable with UTs
