name: Docker

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: docker build -t ghcr.io/hyperledger/firefly-ethconnect:latest .
      
      - name: Tag release
        if: github.event_name == 'release' && github.event.action == 'published'
        run: docker tag ghcr.io/hyperledger/firefly-ethconnect:latest ghcr.io/hyperledger/firefly-ethconnect:$GITHUB_REF
      
      - name: Push docker image
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker push -a ghcr.io/hyperledger/firefly-ethconnect