name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'ethconnect'
      - uses: actions/checkout@v2
        with:
          repository: kaleido-io/ethbinding
          path: 'ethbinding'

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build and Test
        run: cd ethconnect && make

      - name: Upload coverage
        run: bash <(curl -s https://codecov.io/bash)
